### ISSUE TITLE
Setup Project

### ISSUE THREAD

**Issue by iammadanlal** [iammadanlal/os_salon_server#1]
Pull Request should have the followings:-

- [ ] Project should be created for nodejs
- [ ] use any package manager npm, yarn etc.
- [ ] gitignore file for nodejs project
- [ ] basic eslint and prettier config setup
- [ ] Typescript configuration should be there.
- [ ] Base script to run dev server
- [ ] It should have atleast one file to start server.
- [ ] Please paste the screenshot of running server log for example: "Server is running on localhost:4000 to serve for hacktoberfest".

**Comment by Groot-2001** [comment]
Hey @iammadanlal to work on this issue do I need to get assigned ! If yes then could you please add my name as assignee or I'm just working on it I will be create a direct pull request.

**Comment by iammadanlal** [comment]
No need to assign, when you complete the PR, please mention the number of issue. You can do that write # in comment and it will show all the list of issues.

**Comment by iammadanlal** [comment]
@Groot-2001  there is one more repo to make this project workable, link https://github.com/iammadanlal/os_salon_web

**Comment by inbuilt-aura** [comment]
@iammadanlal can i also work on this issue?

**Comment by iammadanlal** [comment]
@inbuilt-aura This is already assigned so you can come with any feature which is not mentioned and create a issue and start work on that. you can put here that feature as well so if you want then i can create that issue from my side. Actually I might be busy in reviewing the PR once people start making PR. So that why I want people to come with new feature request and work on them to make this project better.

**Comment by inbuilt-aura** [comment]
@iammadanlal okay,let me do one thing.I am checking whole site and then whatever issue are there,I will raise issue accordingly and you can check and accept the issue so that I can work on that,is that fine?

**Comment by iammadanlal** [comment]
@inbuilt-aura Thanks, Great!

**Comment by iammadanlal** [comment]
@Groot-2001 Are you working on this, right?

You can add exclude the eslint and prettier and ts configuration later. But can you make quick PR so that other people can start work on other feature.

**Comment by Groot-2001** [comment]
Hey @iammadanlal i almost with all the requirements sooner I'm going to open PR.
