### ISSUE TITLE
Make better folder structure for backend

### ISSUE THREAD

**Issue by Groot-2001** [iammadanlal/os_salon_server#13]
We should plan a better folder structure for code Readability! As we know the more logic gets added the more difficult it can become to understand.

- .vscode	
    - Contains VS Code specific settings
- .github	
    - Contains GitHub settings and configurations, including the GitHub Actions workflows.
- dist	
    - Contains the distributable (or output) from your TypeScript build. 
    - This is the code you ship
- node_modules	
    - Contains all your npm dependencies
- src	
    - Contains your source code that will be compiled to the dist dir
- src/config	
    - Passport authentication strategies and login middleware. Add other complex config code here
- src/controllers	
     - Controllers define functions that respond to various http requests
- src/models	
     - Models define Mongoose schemas that will be used in storing and retrieving data from MongoDB
- src/public	
     - Static assets that will be used client side
- src/types	
    - Holds .d.ts files not found on DefinitelyTyped. Covered more in this section
  
- src/server.ts	
     - Entry point to your express app
- test	
     - Contains your tests. Separate from source because there is a different build process.
    
- .env.example	
     - API keys, tokens, passwords, database URI. Clone this, but don't check it in to public repos.

**Comment by inbuilt-aura** [comment]
hey @Groot-2001 , i would like to work on this issue.Plzz assign me since i am a lot familiar with techstacks.

**Comment by Groot-2001** [comment]
Hey @iammadanlal , this is just my suggestion if your confirmation granted then you could assigned this issue to @inbuilt-aura !

**Comment by iammadanlal** [comment]
@inbuilt-aura Go ahead but I don't think pug will be good idea to use now as most of people only work jsx. So keep the jsx only. I liked the structure, it is looking more modular and scalable now.

**Comment by iammadanlal** [comment]
@inbuilt-aura @Groot-2001 Please support the work, I am doing, by reading following the title & description of issue #12.

**Comment by iammadanlal** [comment]
Share the repo with others as well, Please

**Comment by iammadanlal** [comment]
Share the repo with others as well, Please

**Comment by inbuilt-aura** [comment]
@iammadanlal, on it.

**Comment by inbuilt-aura** [comment]
@Groot-2001 can you give me any example to understand what i have to work on like salon website example,that would be great!

**Comment by inbuilt-aura** [comment]
@iammadanlal, i have opened one issue for frontend component, plzzz check that issue and assign me.Here, i am making all the folder structure and one by one, we will work on every component.

**Comment by iammadanlal** [comment]
@inbuilt-aura can you create only one PR for this issue and #16 as well. and then I also want someone to work on #4 issue.

**Comment by inbuilt-aura** [comment]
@iammadanlal,you want me to build whole project once and then raise pr?I thought like there are total 5 components for 5 pr for each to make things easier.

**Comment by inbuilt-aura** [comment]
@iammadanlal sure

**Comment by iammadanlal** [comment]
@inbuilt-aura  You can create multiple PR but it should be big not just small thing

**Comment by iammadanlal** [comment]
resolved by #20
