### ISSUE TITLE
Create connection with port

### ISSUE THREAD

**Issue by inbuilt-aura** [iammadanlal/os_salon_server#16]
Recreating and formatting whole backend to proper and structured format.Using typescript as a base to write all code. In this issue, updating index.ts and connecting with port,in next issue,will connect with mongodb. @iammadanlal , plzz accept and assign this issue to me, also add the label for hacktoberfest-2023

**Comment by inbuilt-aura** [comment]
@i am submitting this issue,right away, so label it as hacktoberfest and merge my pr

**Comment by iammadanlal** [comment]
Don't need this as server is already running, it means it done already
