### ISSUE TITLE
Setup MongoDB

### ISSUE THREAD

**Issue by iammadanlal** [iammadanlal/os_salon_server#2]
PR must include:-

- [ ] modular code for connecting db
- [ ] create .env.example file for reference to create .env file for running in local
- [ ] Should show connected to db log on starting server.
- [ ] everything should be done in src folder

**Comment by anshul-132002** [comment]
hey! @iammadanlal i want to contribute to this issue

**Comment by iammadanlal** [comment]
Yes, go ahead

**Comment by inbuilt-aura** [comment]
Hey, can i also work on this issue.

**Comment by iammadanlal** [comment]
> Hey, can i also work on this issue.

there is one more repo to make this project workable, link https://github.com/iammadanlal/os_salon_web
